[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc-9"
ar = "aarch64-linux-gnu-ar"
rustflags = [
  "-C", "link-arg=--sysroot=/home/ishant/Projects/OsmOS/Jetson-Toolchain/sysroot",
  "-C", "link-arg=-fuse-ld=gold",
  "-C", "link-arg=-static-libstdc++",
  "-C", "link-arg=-static-libgcc",
  "-C", "target-feature=+crt-static"
]
