[package]
name = "visioncore"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
libloading = "0.8.6"
nokhwa = { version = "0.10.7", features = ["input-native"] }
serde_json = "1.0.140"
visioncore-plugin = { path = "../visioncore-plugin" }
zmq = "0.10.0"
