[package]
name = "locinet"
version = "0.1.0"
edition = "2021"

[lib]
name = "locinet"
crate-type = ["rlib"]  # Changed from "cdylib"

[dependencies]
image = "0.25.6"
tflite = "0.9.8"
visioncore-plugin = { path = "../visioncore-plugin" }