[package]
name = "locinet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
image = "0.25.6"
tract-core = "0.21.11"
tract-tflite = "0.21.11"
visioncore-plugin = { path = "../visioncore-plugin" }
